const cabinetDiscount = [
  { "Company": "Betterply", "MULTIPIER": 0.333 },
  { "Company": "Empire Supplier", "MULTIPIER": 0.333 },
  { "Company": "Goldenhome", "MULTIPIER": 0.333 },
  { "Company": "Instyle Kitchen", "MULTIPIER": 0.333 },
  { "Company": "K&F", "MULTIPIER": 0.333 },
  { "Company": "Luxor Kitchen", "MULTIPIER": 0.333 },
  { "Company": "ZND Productions", "MULTIPIER": 0.333 },
  { "Company": "A&R KITCHEN", "MULTIPIER": 0.34 },
  { "Company": "Acorn Cabinetry", "MULTIPIER": 0.34 },
  { "Company": "BEST HOUSEKEEPING", "MULTIPIER": 0.34 },
  { "Company": "Boro Park Home Decor", "MULTIPIER": 0.34 },
  { "Company": "Budget Maintenance", "MULTIPIER": 0.34 },
  { "Company": "Dash Cabinetry", "MULTIPIER": 0.34 },
  { "Company": "Global Cabinets", "MULTIPIER": 0.35 },
  { "Company": "Jade Kitchen & Bath, Inc", "MULTIPIER": 0.34 },
  { "Company": "KITCHEN EXPO", "MULTIPIER": 0.34 },
  { "Company": "Kitchen Lion", "MULTIPIER": 0.34 },
  { "Company": "Kitchen N Beyond", "MULTIPIER": 0.34 },
  { "Company": "Lamode Kitchens", "MULTIPIER": 0.34 },
  { "Company": "Lincoln Supply", "MULTIPIER": 0.34 },
  { "Company": "Lux Kitchens", "MULTIPIER": 0.34 },
  { "Company": "Martin Cohen", "MULTIPIER": 0.34 },
  { "Company": "Vanguard Kitchen", "MULTIPIER": 0.34 },
  { "Company": "Arozelli Kitchens", "MULTIPIER": 0.35 },
  { "Company": "Bari Enterprise Inc.", "MULTIPIER": 0.35 },
  { "Company": "CREATIVE WOODWORK", "MULTIPIER": 0.35 },
  { "Company": "Express Kitchen & Bath", "MULTIPIER": 0.34 },
  { "Company": "Exquisite Kitchen Design", "MULTIPIER": 0.35 },
  { "Company": "Flex Cabinets", "MULTIPIER": 0.35 },
  { "Company": "Kitchen Art America", "MULTIPIER": 0.35 },
  { "Company": "Kitchen Improvements", "MULTIPIER": 0.35 },
  { "Company": "Modern Kitchen", "MULTIPIER": 0.35 },
  { "Company": "NAGAD CABINETS", "MULTIPIER": 0.35 },
  { "Company": "Rosewood", "MULTIPIER": 0.35 },
  { "Company": "TRI STATE KITCHEN", "MULTIPIER": 0.35 },
  { "Company": "Upgrades NY Inc", "MULTIPIER": 0.35 },
  { "Company": "Crown Kitchens", "MULTIPIER": 0.36 },
  { "Company": "Y&F Construction", "MULTIPIER": 0.36 },
  { "Company": "A&S KITCHENS", "MULTIPIER": 0.38 },
  { "Company": "GREAT LOVE KITCHEN", "MULTIPIER": 0.38 },
  { "Company": "NU Design", "MULTIPIER": 0.38 },
  { "Company": "Optimal Kitchens. LLC", "MULTIPIER": 0.38 },
  { "Company": "P. Hardware", "MULTIPIER": 0.38 },
  { "Company": "UNIVERSAL CABINET", "MULTIPIER": 0.37 },
  { "Company": "Ultimate Kitchens", "MULTIPIER": 0.35 },
  { "Company": "Prestigue Kitchens", "MULTIPIER": 0.37 },
  { "Company": "Beautiful Kitchens", "MULTIPIER": 0.36 },
  { "Company": "Park Kitchen", "MULTIPIER": 0.36 },
  { "Company": "HIGHLINE KITCHEN", "MULTIPIER": 0.36 },
  { "Company": "Dynamic Kitchen", "MULTIPIER": 0.36 },
  { "Company": "Studio Imperial", "MULTIPIER": 0.36 },
  { "Company": "Kitchenette INC.", "MULTIPIER": 0.36 },
  { "Company": "ESF INC.", "MULTIPIER": 0.37 },
  { "Company": "World Class Kitchen", "MULTIPIER": 0.36 },
  { "Company": "Kitchen Experience", "MULTIPIER": 0.35 },
  { "Company": "C kitchen", "MULTIPIER": 0.38 },
  { "Company": "Turf Office", "MULTIPIER": 0.38 },
  { "Company": "Highpoint Kitchens", "MULTIPIER": 0.34 },
  { "Company": "KITCHENS OF USA", "MULTIPIER": 0.36 },
  { "Company": "Woodzters", "MULTIPIER": 0.38 },
  { "Company": "New Era", "MULTIPIER": 0.39 },
  { "Company": "SJF Management", "MULTIPIER": 0.38 },
  { "Company": "EZ Kitchen", "MULTIPIER": 0.38 },
  { "Company": "Prime C Kitchen", "MULTIPIER": 0.38 },
  { "Company": "Polaris Trading", "MULTIPIER": 0.35 },
  { "Company": "ADL Distributors", "MULTIPIER": 0.4 },
  { "Company": "Roselle", "MULTIPIER": 0.38 }
]

export default cabinetDiscount;
